"""
Django settings for taskPrj project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
# False by default, set to True in .env file
DEBUG = os.getenv('DEBUG', default="False")
# DEBUG = False
ALLOWED_HOSTS = [os.getenv('ALLOWED_HOSTS', default='127.0.0.1')]

APP_NAME = os.getenv('APP_NAME', '')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    "crispy_forms",
    "crispy_bootstrap5",
    'drf_yasg',
    'taskApi',
    'taskWebapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'taskPrj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taskPrj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = "files/"
DATASETS_DIR = os.path.join(BASE_DIR, MEDIA_ROOT, 'datasets')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGS_PATH = os.path.join(BASE_DIR, "logs")
if not os.path.exists(LOGS_PATH):
    os.mkdir(LOGS_PATH)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_PATH, APP_NAME+".log"),
            "maxBytes": 1024 * 1024 * 50,  # 50MB
            "backupCount": 7,
            "formatter": "simple",
        },
    },
    "loggers": {
        "django.utils.autoreload": {
            "level": "INFO",
        },
        "django": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Semantic Versioning 2.0.0
# *** update with every release
API_NAME = os.environ.get("APP_NAME")
API_VERSION_MAJOR = "0"
API_VERSION_MINOR = "1"
API_VERSION_PATCH = "0"
RUNNING_ENVIRONMENT = "DEV" if DEBUG else "PROD"
API_CONTACT_EMAIL = os.environ.get("API_CONTACT_EMAIL")


REST_FRAMEWORK = {
    "DEFAULT_VERSION": ""
    + API_VERSION_MAJOR
    + "."
    + API_VERSION_MINOR
    + "."
    + API_VERSION_PATCH
    + "-"
    + RUNNING_ENVIRONMENT,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": False,
    "SECURITY_DEFINITIONS": {"basic": {"type": "basic"}},
    "exclude_namespaces": ["internal_apis"],  # List URL namespaces to ignore
}

# Global settings for different datasets repositories
# reposiroty is MetaboLights
MTBLS_ACC_PREFIX = "MTBLS"
MTBLS_FTP_URL = "ftp.ebi.ac.uk"
MTBLS_FTP_USER = "anonymous"
MTBLS_FTP_USER_PASS = "task_JR538"
MTBLS_FTP_BASE_DIR = "/pub/databases/metabolights/studies/public/"
MTBLS_REMOTE_URL = "https://ftp.ebi.ac.uk/pub/databases/metabolights/studies/public/"
MTBLS_FNAME_INVESTIGATION = "i_Investigation.txt"
MTBLS_FNAME_RESULT_FILES = "rawdata_files.txt"
# reposiroty is Metabolomics-Workbench
MTWB_ACC_PREFIX = "ST"
MTWB_REST_BASE_URL = "https://www.metabolomicsworkbench.org"
MTWB_FNAME_JSON_SUFIX = ".json"
MTWB_FNAME_MWTAB_SUFIX = ".mwtab.txt"
# reposiroty is MetaboBank
MTBK_ACC_PREFIX = "MTBK"
MTBK_BASE_URL = "https://ddbj.nig.ac.jp/public/metabobank"
MTBK_STUDY_CONTEXT = "study"
MTBK_IDF_FILE_PREFIX = ".idf"
MTBK_SDRF_FILE_PREFIX = ".sdrf"
MTBK_FILELIST_FILE_PREFIX = ".filelist"
MTBK_MAF_FILE_PREFIX = ".maf"
MTBK_FILES_SUFIX = ".txt"
